-- Tabla de inscripciones (participantes) a actividades educativas.
-- Ejecutar en MySQL (phpMyAdmin o consola). Tipos INT sin UNSIGNED para coincidir con las tablas existentes.

CREATE TABLE IF NOT EXISTS TAB_INSCRIPCIONES_ACTIVIDADES (
    ID_INSCRIPCION INT NOT NULL AUTO_INCREMENT,
    ID_ACTIVIDAD_EDUCACION INT NOT NULL,
    ID_ESTUDIANTE INT NOT NULL,
    FECHA_INSCRIPCION DATE NULL,
    ESTADO VARCHAR(20) DEFAULT 'Inscrito',
    PRIMARY KEY (ID_INSCRIPCION),
    UNIQUE KEY uk_actividad_estudiante (ID_ACTIVIDAD_EDUCACION, ID_ESTUDIANTE),
    CONSTRAINT fk_insc_actividad FOREIGN KEY (ID_ACTIVIDAD_EDUCACION) REFERENCES TAB_ACTIVIDADES_EDUCACION (ID_ACTIVIDAD_EDUCACION) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_insc_estudiante FOREIGN KEY (ID_ESTUDIANTE) REFERENCES TAB_ESTUDIANTES (ID_ESTUDIANTE) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
