-- =============================================================================
-- Migración: TAB_PERIODOS_ACADEMICOS — FECHA_INICIO/FECHA_FIN → MES/AÑO inicio y fin
-- =============================================================================
--
-- >>> IMPORTASTE bddITSI.sql COMPLETO OTRA VEZ (instalación nueva):
--     La tabla TAB_PERIODOS_ACADEMICOS ya viene con MES_INICIO / AÑO_INICIO / MES_FIN / AÑO_FIN.
--     NO ejecutes el bloque desde "ALTER TABLE TAB_PERIODOS_ACADEMICOS ADD COLUMN..." hasta
--     el segundo "ALTER TABLE ... ADD INDEX IF NOT EXISTS" (aprox. líneas 34–90).
--     Puedes ejecutar solo la parte de DROP/CREATE vistas y procedimientos si los necesitas al día.
--
-- La definición canónica: bddITSI.sql — TAB_PERIODOS_ACADEMICOS solo ID + mes/año inicio y fin.
--
-- Modificar bddITSI.sql NO actualiza MySQL. Ejecuta este archivo en phpMyAdmin (pestaña SQL).
-- En phpMyAdmin selecciona antes tu base de datos (ej. `itsi`) en el panel izquierdo.
-- Base de datos: itsi
--
-- Re-ejecutar el script: usa IF NOT EXISTS en ADD COLUMN (MariaDB / XAMPP habitual).
-- Si tu motor es MySQL puro antiguo y da error de sintaxis en IF NOT EXISTS:
--   comenta el bloque ALTER ADD COLUMN y sigue desde el UPDATE (si aún existen FECHA_*).
-- Si ya no tienes FECHA_INICIO/FECHA_FIN, NO ejecutes UPDATE ni DROP COLUMN; salta al MODIFY.
-- Error #1054 "FECHA_INICIO desconocida": esas columnas ya se eliminaron. NO lances el UPDATE a mano;
--   si MES_INICIO/AÑO_* ya tienen datos, sigue con MODIFY + índice + vistas. Si están NULL y perdiste
--   las fechas, solo se recupera desde un respaldo de BD.
-- Si DROP INDEX falla, ejecuta SHOW INDEX FROM TAB_PERIODOS_ACADEMICOS; y ajusta el nombre.
-- =============================================================================

USE `itsi`;

DROP PROCEDURE IF EXISTS SP_DOCUMENTOS_POR_PERIODO;
DROP PROCEDURE IF EXISTS SP_ESTADISTICAS_PERIODO;
DROP PROCEDURE IF EXISTS SP_OBTENER_PERIODO_ACTUAL;

DROP VIEW IF EXISTS V_DOCUMENTOS_POR_PERIODO;
DROP VIEW IF EXISTS V_ESTADISTICAS_PERIODOS;
DROP VIEW IF EXISTS V_PRACTICAS_POR_PERIODO;
DROP VIEW IF EXISTS V_SERVICIOS_POR_PERIODO;
DROP VIEW IF EXISTS V_PERIODO_ACADEMICO_ACTUAL;
DROP VIEW IF EXISTS V_PERIODOS_ACADEMICOS_ORDENADOS;
DROP VIEW IF EXISTS V_DOCUMENTOS_UNIFICADOS;
DROP VIEW IF EXISTS V_DOCUMENTOS_PRACTICAS_COMPLETOS;
DROP VIEW IF EXISTS V_DOCUMENTOS_SERVICIO_COMPLETOS;

-- ========== INICIO: solo BDs con FECHA_INICIO/FECHA_FIN en TAB_PERIODOS_ACADEMICOS ==========
-- Omitir todo este bloque si importaste bddITSI.sql (períodos ya en mes/año).
ALTER TABLE TAB_PERIODOS_ACADEMICOS
  ADD COLUMN IF NOT EXISTS MES_INICIO TINYINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS AÑO_INICIO INT NULL,
  ADD COLUMN IF NOT EXISTS MES_FIN TINYINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS AÑO_FIN INT NULL;

-- Comprobar columnas (opcional, en una pestaña SQL aparte):
-- SELECT COLUMN_NAME FROM information_schema.COLUMNS
--   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TAB_PERIODOS_ACADEMICOS'
--   AND COLUMN_NAME IN ('FECHA_INICIO','FECHA_FIN');
-- Si no devuelve 2 filas, omite el bloque siguiente (CALL ...): ya no hay fechas que copiar.

DROP PROCEDURE IF EXISTS SP_TMP_MIGRAR_PERIODOS_FECHAS_A_MES_ANIO;

DELIMITER //
CREATE PROCEDURE SP_TMP_MIGRAR_PERIODOS_FECHAS_A_MES_ANIO()
BEGIN
  -- Solo copia y borra FECHA_* si ambas columnas siguen existiendo (re-ejecución segura).
  IF (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'TAB_PERIODOS_ACADEMICOS'
        AND COLUMN_NAME IN ('FECHA_INICIO', 'FECHA_FIN')) = 2 THEN
    UPDATE TAB_PERIODOS_ACADEMICOS SET
      MES_INICIO = MONTH(FECHA_INICIO),
      AÑO_INICIO = YEAR(FECHA_INICIO),
      MES_FIN = MONTH(FECHA_FIN),
      AÑO_FIN = YEAR(FECHA_FIN)
    WHERE FECHA_INICIO IS NOT NULL AND FECHA_FIN IS NOT NULL;

    -- No uses un nombre de índice fijo: en tu servidor puede no existir IDX_FECHA_INICIO_PERIODO.
    -- Si DROP COLUMN falla por índice: SHOW INDEX FROM TAB_PERIODOS_ACADEMICOS; y DROP INDEX <Key_name>.
    ALTER TABLE TAB_PERIODOS_ACADEMICOS
      DROP COLUMN FECHA_INICIO,
      DROP COLUMN FECHA_FIN;
  END IF;
END//
DELIMITER ;

CALL SP_TMP_MIGRAR_PERIODOS_FECHAS_A_MES_ANIO();

DROP PROCEDURE IF EXISTS SP_TMP_MIGRAR_PERIODOS_FECHAS_A_MES_ANIO;

-- phpMyAdmin: NO mezcles MODIFY + ADD INDEX en un solo ALTER si el índice puede existir ya:
-- con #1061 (clave duplicada) falla TODA la sentencia y los NOT NULL no se aplican.
-- 1) Ejecuta primero el bloque de MODIFY. 2) Luego el del índice (o omítelo si ya existe).

ALTER TABLE TAB_PERIODOS_ACADEMICOS
  MODIFY MES_INICIO TINYINT UNSIGNED NOT NULL,
  MODIFY AÑO_INICIO INT NOT NULL,
  MODIFY MES_FIN TINYINT UNSIGNED NOT NULL,
  MODIFY AÑO_FIN INT NOT NULL;

-- MariaDB (XAMPP habitual): IF NOT EXISTS evita #1061 al re-ejecutar.
-- MySQL puro sin esa sintaxis: comenta la línea siguiente y, solo si no existe el índice, ejecuta:
--   ALTER TABLE TAB_PERIODOS_ACADEMICOS ADD INDEX IDX_PERIODO_MES_ANIO_INICIO (AÑO_INICIO, MES_INICIO);
ALTER TABLE TAB_PERIODOS_ACADEMICOS
  ADD INDEX IF NOT EXISTS IDX_PERIODO_MES_ANIO_INICIO (AÑO_INICIO, MES_INICIO);

-- ========== FIN: solo BDs legadas (períodos) ==========

-- === Vistas (misma definición que bddITSI.sql) ===
CREATE OR REPLACE VIEW V_DOCUMENTOS_PRACTICAS_COMPLETOS AS
SELECT 
    dp.ID_DOCUMENTO_PREPROFESIONAL,
    dp.ID_PRACTICA_PREPROFESIONAL,
    dp.ID_TIPO_DOCUMENTO,
    dp.ID_ESTADO_REVISION,
    dp.NOMBRE_ARCHIVO,
    dp.NOMBRE_ORIGINAL,
    dp.TIPO_ARCHIVO,
    dp.TAMANO_ARCHIVO,
    dp.RUTA_ARCHIVO,
    dp.FECHA_SUBIDA,
    dp.FECHA_REVISION,
    dp.ID_REVISOR,
    dp.OBSERVACIONES,
    dp.OBSERVACIONES_REVISOR,
    dp.VERSION,
    dp.ACTIVO,
    'PRACTICAS' as TIPO_MODALIDAD,
    
    -- Información del período académico (tabla: solo mes/año inicio-fin; resto derivado)
    pp.ID_PERIODO_ACADEMICO,
    CONCAT(LPAD(pa.MES_INICIO, 2, '0'), '/', pa.AÑO_INICIO, ' - ', LPAD(pa.MES_FIN, 2, '0'), '/', pa.AÑO_FIN) AS NOMBRE_PERIODO,
    pa.AÑO_INICIO AS AÑO_ACADEMICO,
    pa.MES_INICIO,
    pa.AÑO_INICIO,
    pa.MES_FIN,
    pa.AÑO_FIN,
    STR_TO_DATE(CONCAT(pa.AÑO_INICIO, '-', LPAD(pa.MES_INICIO, 2, '0'), '-01'), '%Y-%m-%d') AS PERIODO_FECHA_INICIO,
    LAST_DAY(STR_TO_DATE(CONCAT(pa.AÑO_FIN, '-', LPAD(pa.MES_FIN, 2, '0'), '-01'), '%Y-%m-%d')) AS PERIODO_FECHA_FIN,
    'N/D' AS TIPO_PERIODO,
    0 AS NUMERO_PERIODO,
    NULL AS PERIODO_ESTADO,
    CONCAT(LPAD(pa.MES_INICIO, 2, '0'), '/', pa.AÑO_INICIO, ' - ', LPAD(pa.MES_FIN, 2, '0'), '/', pa.AÑO_FIN) AS PERIODO_COMPLETO,
    
    -- Información del tipo de documento
    tdp.CODIGO as TIPO_DOCUMENTO_CODIGO,
    tdp.NOMBRE as TIPO_DOCUMENTO_NOMBRE,
    tdp.DESCRIPCION as TIPO_DOCUMENTO_DESCRIPCION,
    tdp.ORDEN as TIPO_DOCUMENTO_ORDEN,
    tdp.OBLIGATORIO as TIPO_DOCUMENTO_OBLIGATORIO,
    
    -- Información del estado
    er.ESTADO as ESTADO_REVISION,
    er.DESCRIPCION as ESTADO_DESCRIPCION,
    er.COLOR as ESTADO_COLOR,
    
    -- Información del estudiante
    pp.ID_ESTUDIANTE,
    CONCAT(persona.NOMBRE, ' ', persona.APELLIDO) as ESTUDIANTE_NOMBRE,
    persona.NOMBRE as NOMBRE_ESTUDIANTE,
    persona.APELLIDO as APELLIDO_ESTUDIANTE,
    persona.CEDULA as CEDULA_ESTUDIANTE,
    
    -- Información de la entidad receptora
    ic.NOMBRE as ENTIDAD_RECEPTORA,
    ic.RUC as ENTIDAD_RUC,
    ic.CIUDAD as ENTIDAD_CIUDAD,
    
    -- Información del revisor
    CONCAT(rev_persona.NOMBRE, ' ', rev_persona.APELLIDO) as REVISOR_NOMBRE,
    rev_persona.NOMBRE as NOMBRE_REVISOR,
    rev_persona.APELLIDO as APELLIDO_REVISOR,
    
    -- Información del docente tutor
    CONCAT(dt_persona.NOMBRE, ' ', dt_persona.APELLIDO) as DOCENTE_TUTOR,
    dt_persona.NOMBRE as NOMBRE_DOCENTE,
    dt_persona.APELLIDO as APELLIDO_DOCENTE,
    dt.ESPECIALIDAD as DOCENTE_ESPECIALIDAD,
    dt.TITULO_PROFESIONAL as DOCENTE_TITULO

FROM TAB_DOCUMENTOS_PRACTICAS_PREPROFESIONALES dp
LEFT JOIN TAB_TIPOS_DOCUMENTOS_PREPROFESIONALES tdp ON dp.ID_TIPO_DOCUMENTO = tdp.ID_TIPO_DOCUMENTO_PREPROFESIONAL
LEFT JOIN TAB_ESTADOS_REVISIONES er ON dp.ID_ESTADO_REVISION = er.ID_ESTADO_REVISION
LEFT JOIN TAB_PRACTICAS_PREPROFESIONALES pp ON dp.ID_PRACTICA_PREPROFESIONAL = pp.ID_PRACTICA_PREPROFESIONAL
LEFT JOIN TAB_PERIODOS_ACADEMICOS pa ON pp.ID_PERIODO_ACADEMICO = pa.ID_PERIODO_ACADEMICO
LEFT JOIN TAB_ESTUDIANTES e ON pp.ID_ESTUDIANTE = e.ID_ESTUDIANTE
LEFT JOIN TAB_DATOS_PERSONAS persona ON e.ID_DATO_PERSONA = persona.ID_DATO_PERSONA
LEFT JOIN TAB_INSTITUCIONES_CONVENIOS ic ON pp.ID_INSTITUCION_CONVENIO = ic.ID_INSTITUCION_CONVENIO
LEFT JOIN TAB_USUARIOS rev_usuario ON dp.ID_REVISOR = rev_usuario.ID_USUARIO
LEFT JOIN TAB_DATOS_PERSONAS rev_persona ON rev_usuario.ID_DATO_PERSONA = rev_persona.ID_DATO_PERSONA
LEFT JOIN TAB_ASIGNACIONES_DOCENTES_PRACTICAS adp ON pp.ID_PRACTICA_PREPROFESIONAL = adp.ID_PRACTICA_PREPROFESIONAL AND adp.TIPO_ASIGNACION = 'Principal'
LEFT JOIN TAB_DOCENTES_TUTORES dt ON adp.ID_DOCENTE_TUTOR = dt.ID_DOCENTE_TUTOR
LEFT JOIN TAB_USUARIOS dt_usuario ON dt.ID_USUARIO = dt_usuario.ID_USUARIO
LEFT JOIN TAB_DATOS_PERSONAS dt_persona ON dt_usuario.ID_DATO_PERSONA = dt_persona.ID_DATO_PERSONA
WHERE dp.ACTIVO = true;

-- Vista para documentos de servicio comunitario
CREATE OR REPLACE VIEW V_DOCUMENTOS_SERVICIO_COMPLETOS AS
SELECT 
    ds.ID_DOCUMENTO_SERVICIO as ID_DOCUMENTO_PREPROFESIONAL,
    ds.ID_SERVICIO_COMUNITARIO as ID_PRACTICA_PREPROFESIONAL,
    ds.ID_TIPO_DOCUMENTO,
    ds.ID_ESTADO_REVISION,
    ds.NOMBRE_ARCHIVO,
    ds.NOMBRE_ORIGINAL,
    ds.TIPO_ARCHIVO,
    ds.TAMANO_ARCHIVO,
    ds.RUTA_ARCHIVO,
    ds.FECHA_SUBIDA,
    ds.FECHA_REVISION,
    ds.ID_REVISOR,
    ds.OBSERVACIONES,
    ds.OBSERVACIONES_REVISOR,
    ds.VERSION,
    ds.ACTIVO,
    'SERVICIO_COMUNITARIO' as TIPO_MODALIDAD,
    
    -- Información del período académico (tabla: solo mes/año inicio-fin; resto derivado)
    sc.ID_PERIODO_ACADEMICO,
    CONCAT(LPAD(pa.MES_INICIO, 2, '0'), '/', pa.AÑO_INICIO, ' - ', LPAD(pa.MES_FIN, 2, '0'), '/', pa.AÑO_FIN) AS NOMBRE_PERIODO,
    pa.AÑO_INICIO AS AÑO_ACADEMICO,
    pa.MES_INICIO,
    pa.AÑO_INICIO,
    pa.MES_FIN,
    pa.AÑO_FIN,
    STR_TO_DATE(CONCAT(pa.AÑO_INICIO, '-', LPAD(pa.MES_INICIO, 2, '0'), '-01'), '%Y-%m-%d') AS PERIODO_FECHA_INICIO,
    LAST_DAY(STR_TO_DATE(CONCAT(pa.AÑO_FIN, '-', LPAD(pa.MES_FIN, 2, '0'), '-01'), '%Y-%m-%d')) AS PERIODO_FECHA_FIN,
    'N/D' AS TIPO_PERIODO,
    0 AS NUMERO_PERIODO,
    NULL AS PERIODO_ESTADO,
    CONCAT(LPAD(pa.MES_INICIO, 2, '0'), '/', pa.AÑO_INICIO, ' - ', LPAD(pa.MES_FIN, 2, '0'), '/', pa.AÑO_FIN) AS PERIODO_COMPLETO,
    
    -- Información del tipo de documento
    tds.CODIGO as TIPO_DOCUMENTO_CODIGO,
    tds.NOMBRE as TIPO_DOCUMENTO_NOMBRE,
    tds.DESCRIPCION as TIPO_DOCUMENTO_DESCRIPCION,
    tds.ORDEN as TIPO_DOCUMENTO_ORDEN,
    tds.OBLIGATORIO as TIPO_DOCUMENTO_OBLIGATORIO,
    
    -- Información del estado
    er.ESTADO as ESTADO_REVISION,
    er.DESCRIPCION as ESTADO_DESCRIPCION,
    er.COLOR as ESTADO_COLOR,
    
    -- Información del estudiante
    sc.ID_ESTUDIANTE,
    CONCAT(persona.NOMBRE, ' ', persona.APELLIDO) as ESTUDIANTE_NOMBRE,
    persona.NOMBRE as NOMBRE_ESTUDIANTE,
    persona.APELLIDO as APELLIDO_ESTUDIANTE,
    persona.CEDULA as CEDULA_ESTUDIANTE,
    
    -- Información de la entidad receptora
    ic.NOMBRE as ENTIDAD_RECEPTORA,
    ic.RUC as ENTIDAD_RUC,
    ic.CIUDAD as ENTIDAD_CIUDAD,
    
    -- Información del revisor
    CONCAT(rev_persona.NOMBRE, ' ', rev_persona.APELLIDO) as REVISOR_NOMBRE,
    rev_persona.NOMBRE as NOMBRE_REVISOR,
    rev_persona.APELLIDO as APELLIDO_REVISOR,
    
    -- Información del docente tutor
    CONCAT(dt_persona.NOMBRE, ' ', dt_persona.APELLIDO) as DOCENTE_TUTOR,
    dt_persona.NOMBRE as NOMBRE_DOCENTE,
    dt_persona.APELLIDO as APELLIDO_DOCENTE,
    dt.ESPECIALIDAD as DOCENTE_ESPECIALIDAD,
    dt.TITULO_PROFESIONAL as DOCENTE_TITULO

FROM TAB_DOCUMENTOS_SERVICIO_COMUNITARIO ds
LEFT JOIN TAB_TIPOS_DOCUMENTOS_SERVICIO_COMUNITARIO tds ON ds.ID_TIPO_DOCUMENTO = tds.ID_TIPO_DOCUMENTO_SERVICIO
LEFT JOIN TAB_ESTADOS_REVISIONES er ON ds.ID_ESTADO_REVISION = er.ID_ESTADO_REVISION
LEFT JOIN TAB_SERVICIO_COMUNITARIO sc ON ds.ID_SERVICIO_COMUNITARIO = sc.ID_SERVICIO_COMUNITARIO
LEFT JOIN TAB_PERIODOS_ACADEMICOS pa ON sc.ID_PERIODO_ACADEMICO = pa.ID_PERIODO_ACADEMICO
LEFT JOIN TAB_ESTUDIANTES e ON sc.ID_ESTUDIANTE = e.ID_ESTUDIANTE
LEFT JOIN TAB_DATOS_PERSONAS persona ON e.ID_DATO_PERSONA = persona.ID_DATO_PERSONA
LEFT JOIN TAB_INSTITUCIONES_CONVENIOS ic ON sc.ID_INSTITUCION_CONVENIO = ic.ID_INSTITUCION_CONVENIO
LEFT JOIN TAB_USUARIOS rev_usuario ON ds.ID_REVISOR = rev_usuario.ID_USUARIO
LEFT JOIN TAB_DATOS_PERSONAS rev_persona ON rev_usuario.ID_DATO_PERSONA = rev_persona.ID_DATO_PERSONA
LEFT JOIN TAB_ASIGNACIONES_DOCENTES_PRACTICAS adp ON sc.ID_SERVICIO_COMUNITARIO = adp.ID_SERVICIO_COMUNITARIO AND adp.TIPO_ASIGNACION = 'Principal'
LEFT JOIN TAB_DOCENTES_TUTORES dt ON adp.ID_DOCENTE_TUTOR = dt.ID_DOCENTE_TUTOR
LEFT JOIN TAB_USUARIOS dt_usuario ON dt.ID_USUARIO = dt_usuario.ID_USUARIO
LEFT JOIN TAB_DATOS_PERSONAS dt_persona ON dt_usuario.ID_DATO_PERSONA = dt_persona.ID_DATO_PERSONA
WHERE ds.ACTIVO = true;

-- Vista unificada para ambos tipos
CREATE OR REPLACE VIEW V_DOCUMENTOS_UNIFICADOS AS
SELECT * FROM V_DOCUMENTOS_PRACTICAS_COMPLETOS
UNION ALL
SELECT * FROM V_DOCUMENTOS_SERVICIO_COMPLETOS
ORDER BY FECHA_SUBIDA DESC;

-- ==============================================================
-- VISTAS ESPECIALIZADAS PARA PERÍODOS ACADÉMICOS
-- ==============================================================

-- Vista para obtener el período académico actual (inicio más reciente)
CREATE OR REPLACE VIEW V_PERIODO_ACADEMICO_ACTUAL AS
SELECT 
    ID_PERIODO_ACADEMICO,
    CONCAT(LPAD(MES_INICIO, 2, '0'), '/', AÑO_INICIO, ' - ', LPAD(MES_FIN, 2, '0'), '/', AÑO_FIN) AS NOMBRE_PERIODO,
    AÑO_INICIO AS AÑO_ACADEMICO,
    MES_INICIO,
    AÑO_INICIO,
    MES_FIN,
    AÑO_FIN,
    STR_TO_DATE(CONCAT(AÑO_INICIO, '-', LPAD(MES_INICIO, 2, '0'), '-01'), '%Y-%m-%d') AS FECHA_INICIO,
    LAST_DAY(STR_TO_DATE(CONCAT(AÑO_FIN, '-', LPAD(MES_FIN, 2, '0'), '-01'), '%Y-%m-%d')) AS FECHA_FIN,
    'N/D' AS TIPO_PERIODO,
    0 AS NUMERO_PERIODO,
    'N/D' AS ESTADO,
    NULL AS DESCRIPCION,
    CONCAT(LPAD(MES_INICIO, 2, '0'), '/', AÑO_INICIO, ' - ', LPAD(MES_FIN, 2, '0'), '/', AÑO_FIN) AS PERIODO_COMPLETO
FROM TAB_PERIODOS_ACADEMICOS
ORDER BY AÑO_INICIO DESC, MES_INICIO DESC
LIMIT 1;

-- Vista para obtener todos los períodos académicos ordenados
CREATE OR REPLACE VIEW V_PERIODOS_ACADEMICOS_ORDENADOS AS
SELECT 
    ID_PERIODO_ACADEMICO,
    CONCAT(LPAD(MES_INICIO, 2, '0'), '/', AÑO_INICIO, ' - ', LPAD(MES_FIN, 2, '0'), '/', AÑO_FIN) AS NOMBRE_PERIODO,
    AÑO_INICIO AS AÑO_ACADEMICO,
    MES_INICIO,
    AÑO_INICIO,
    MES_FIN,
    AÑO_FIN,
    STR_TO_DATE(CONCAT(AÑO_INICIO, '-', LPAD(MES_INICIO, 2, '0'), '-01'), '%Y-%m-%d') AS FECHA_INICIO,
    LAST_DAY(STR_TO_DATE(CONCAT(AÑO_FIN, '-', LPAD(MES_FIN, 2, '0'), '-01'), '%Y-%m-%d')) AS FECHA_FIN,
    'N/D' AS TIPO_PERIODO,
    0 AS NUMERO_PERIODO,
    'N/D' AS ESTADO,
    NULL AS DESCRIPCION,
    CONCAT(LPAD(MES_INICIO, 2, '0'), '/', AÑO_INICIO, ' - ', LPAD(MES_FIN, 2, '0'), '/', AÑO_FIN) AS PERIODO_COMPLETO,
    0 AS ORDEN_ESTADO
FROM TAB_PERIODOS_ACADEMICOS
ORDER BY AÑO_INICIO DESC, MES_INICIO DESC;

-- Vista para estadísticas por período académico
CREATE OR REPLACE VIEW V_ESTADISTICAS_PERIODOS AS
SELECT 
    pa.ID_PERIODO_ACADEMICO,
    CONCAT(LPAD(pa.MES_INICIO, 2, '0'), '/', pa.AÑO_INICIO, ' - ', LPAD(pa.MES_FIN, 2, '0'), '/', pa.AÑO_FIN) AS NOMBRE_PERIODO,
    pa.AÑO_INICIO AS AÑO_ACADEMICO,
    'N/D' AS TIPO_PERIODO,
    NULL AS ESTADO,
    CONCAT(LPAD(pa.MES_INICIO, 2, '0'), '/', pa.AÑO_INICIO, ' - ', LPAD(pa.MES_FIN, 2, '0'), '/', pa.AÑO_FIN) AS PERIODO_COMPLETO,
    
    -- Estadísticas de prácticas preprofesionales
    COUNT(DISTINCT pp.ID_PRACTICA_PREPROFESIONAL) as TOTAL_PRACTICAS_PREPROFESIONALES,
    COUNT(DISTINCT CASE WHEN pp.ESTADO_PRACTICA = 'En Progreso' THEN pp.ID_PRACTICA_PREPROFESIONAL END) as PRACTICAS_EN_PROGRESO,
    COUNT(DISTINCT CASE WHEN pp.ESTADO_PRACTICA = 'Completada' THEN pp.ID_PRACTICA_PREPROFESIONAL END) as PRACTICAS_COMPLETADAS,
    COUNT(DISTINCT CASE WHEN pp.ESTADO_PRACTICA = 'Cancelada' THEN pp.ID_PRACTICA_PREPROFESIONAL END) as PRACTICAS_CANCELADAS,
    
    -- Estadísticas de servicio comunitario
    COUNT(DISTINCT sc.ID_SERVICIO_COMUNITARIO) as TOTAL_SERVICIOS_COMUNITARIOS,
    COUNT(DISTINCT CASE WHEN sc.ESTADO_SERVICIO = 'En Progreso' THEN sc.ID_SERVICIO_COMUNITARIO END) as SERVICIOS_EN_PROGRESO,
    COUNT(DISTINCT CASE WHEN sc.ESTADO_SERVICIO = 'Completado' THEN sc.ID_SERVICIO_COMUNITARIO END) as SERVICIOS_COMPLETADOS,
    COUNT(DISTINCT CASE WHEN sc.ESTADO_SERVICIO = 'Cancelado' THEN sc.ID_SERVICIO_COMUNITARIO END) as SERVICIOS_CANCELADOS,
    
    -- Estadísticas de actividades educativas
    COUNT(DISTINCT ae.ID_ACTIVIDAD_EDUCACION) as TOTAL_ACTIVIDADES_EDUCATIVAS,
    
    -- Estadísticas de estudiantes
    COUNT(DISTINCT e.ID_ESTUDIANTE) as TOTAL_ESTUDIANTES_PARTICIPANTES,
    
    -- Estadísticas de documentos
    COUNT(DISTINCT dp.ID_DOCUMENTO_PREPROFESIONAL) as TOTAL_DOCUMENTOS_PRACTICAS,
    COUNT(DISTINCT ds.ID_DOCUMENTO_SERVICIO) as TOTAL_DOCUMENTOS_SERVICIO,
    
    -- Rango del período (derivado de mes/año; útil para reportes)
    STR_TO_DATE(CONCAT(pa.AÑO_INICIO, '-', LPAD(pa.MES_INICIO, 2, '0'), '-01'), '%Y-%m-%d') AS FECHA_INICIO,
    LAST_DAY(STR_TO_DATE(CONCAT(pa.AÑO_FIN, '-', LPAD(pa.MES_FIN, 2, '0'), '-01'), '%Y-%m-%d')) AS FECHA_FIN,
    DATEDIFF(
        LAST_DAY(STR_TO_DATE(CONCAT(pa.AÑO_FIN, '-', LPAD(pa.MES_FIN, 2, '0'), '-01'), '%Y-%m-%d')),
        STR_TO_DATE(CONCAT(pa.AÑO_INICIO, '-', LPAD(pa.MES_INICIO, 2, '0'), '-01'), '%Y-%m-%d')
    ) + 1 AS DIAS_DURACION

FROM TAB_PERIODOS_ACADEMICOS pa
LEFT JOIN TAB_PRACTICAS_PREPROFESIONALES pp ON pa.ID_PERIODO_ACADEMICO = pp.ID_PERIODO_ACADEMICO
LEFT JOIN TAB_SERVICIO_COMUNITARIO sc ON pa.ID_PERIODO_ACADEMICO = sc.ID_PERIODO_ACADEMICO
LEFT JOIN TAB_ACTIVIDADES_EDUCACION ae ON pa.ID_PERIODO_ACADEMICO = ae.ID_PERIODO_ACADEMICO
LEFT JOIN TAB_ESTUDIANTES e ON (pp.ID_ESTUDIANTE = e.ID_ESTUDIANTE OR sc.ID_ESTUDIANTE = e.ID_ESTUDIANTE)
LEFT JOIN TAB_DOCUMENTOS_PRACTICAS_PREPROFESIONALES dp ON pp.ID_PRACTICA_PREPROFESIONAL = dp.ID_PRACTICA_PREPROFESIONAL
LEFT JOIN TAB_DOCUMENTOS_SERVICIO_COMUNITARIO ds ON sc.ID_SERVICIO_COMUNITARIO = ds.ID_SERVICIO_COMUNITARIO
GROUP BY pa.ID_PERIODO_ACADEMICO, pa.MES_INICIO, pa.AÑO_INICIO, pa.MES_FIN, pa.AÑO_FIN
ORDER BY pa.AÑO_INICIO DESC, pa.MES_INICIO DESC;

-- Vista para documentos filtrados por período académico
CREATE OR REPLACE VIEW V_DOCUMENTOS_POR_PERIODO AS
SELECT vd.*
FROM V_DOCUMENTOS_UNIFICADOS vd
INNER JOIN TAB_PERIODOS_ACADEMICOS pa ON vd.ID_PERIODO_ACADEMICO = pa.ID_PERIODO_ACADEMICO
ORDER BY pa.AÑO_INICIO DESC, pa.MES_INICIO DESC, vd.FECHA_SUBIDA DESC;

-- Vista para prácticas por período académico
CREATE OR REPLACE VIEW V_PRACTICAS_POR_PERIODO AS
SELECT 
    pp.ID_PRACTICA_PREPROFESIONAL,
    pp.ID_ASIGNACION_PRACTICA,
    pp.ID_ESTUDIANTE,
    pp.ID_INSTRUCTOR,
    pp.ID_INSTITUCION_CONVENIO,
    pp.AREA_ESPECIALIZACION,
    pp.PROYECTO_ESPECIFICO,
    pp.HORAS_PRACTICAS,
    pp.FECHA_INICIO,
    pp.FECHA_FIN,
    pp.ESTADO_PRACTICA,
    pp.EVALUACION_FINAL,
    pp.OBSERVACIONES,
    pp.ID_PERIODO_ACADEMICO,
    
    -- Información del período académico (derivada de mes/año)
    CONCAT(LPAD(pa.MES_INICIO, 2, '0'), '/', pa.AÑO_INICIO, ' - ', LPAD(pa.MES_FIN, 2, '0'), '/', pa.AÑO_FIN) AS NOMBRE_PERIODO,
    pa.AÑO_INICIO AS AÑO_ACADEMICO,
    'N/D' AS TIPO_PERIODO,
    NULL AS PERIODO_ESTADO,
    CONCAT(LPAD(pa.MES_INICIO, 2, '0'), '/', pa.AÑO_INICIO, ' - ', LPAD(pa.MES_FIN, 2, '0'), '/', pa.AÑO_FIN) AS PERIODO_COMPLETO,
    
    -- Información del estudiante
    CONCAT(persona.NOMBRE, ' ', persona.APELLIDO) as ESTUDIANTE_NOMBRE,
    persona.CEDULA as CEDULA_ESTUDIANTE,
    c.NOMBRE as CARRERA_NOMBRE,
    e.SEMESTRE_ACTUAL,
    
    -- Información de la entidad receptora
    ic.NOMBRE as ENTIDAD_RECEPTORA,
    ic.CIUDAD as ENTIDAD_CIUDAD,
    
    -- Información del instructor
    CONCAT(inst_persona.NOMBRE, ' ', inst_persona.APELLIDO) as INSTRUCTOR_NOMBRE,
    inst.ESPECIALIDAD as INSTRUCTOR_ESPECIALIDAD

FROM TAB_PRACTICAS_PREPROFESIONALES pp
LEFT JOIN TAB_PERIODOS_ACADEMICOS pa ON pp.ID_PERIODO_ACADEMICO = pa.ID_PERIODO_ACADEMICO
LEFT JOIN TAB_ESTUDIANTES e ON pp.ID_ESTUDIANTE = e.ID_ESTUDIANTE
LEFT JOIN TAB_DATOS_PERSONAS persona ON e.ID_DATO_PERSONA = persona.ID_DATO_PERSONA
LEFT JOIN TAB_CARRERAS c ON e.ID_CARRERA = c.ID_CARRERA
LEFT JOIN TAB_INSTITUCIONES_CONVENIOS ic ON pp.ID_INSTITUCION_CONVENIO = ic.ID_INSTITUCION_CONVENIO
LEFT JOIN TAB_INSTRUCTORES inst ON pp.ID_INSTRUCTOR = inst.ID_INSTRUCTOR
LEFT JOIN TAB_DATOS_PERSONAS inst_persona ON inst.ID_DATO_PERSONA = inst_persona.ID_DATO_PERSONA
ORDER BY pa.AÑO_INICIO DESC, pa.MES_INICIO DESC, pp.FECHA_INICIO DESC;

-- Vista para servicios comunitarios por período académico
CREATE OR REPLACE VIEW V_SERVICIOS_POR_PERIODO AS
SELECT 
    sc.ID_SERVICIO_COMUNITARIO,
    sc.ID_ASIGNACION_PRACTICA,
    sc.ID_ESTUDIANTE,
    sc.ID_INSTRUCTOR,
    sc.ID_INSTITUCION_CONVENIO,
    sc.PROYECTO_SOCIAL,
    sc.COMUNIDAD_BENEFICIADA,
    sc.HORAS_SERVICIO,
    sc.FECHA_INICIO,
    sc.FECHA_FIN,
    sc.ESTADO_SERVICIO,
    sc.IMPACTO_SOCIAL,
    sc.OBSERVACIONES,
    sc.ID_PERIODO_ACADEMICO,
    
    -- Información del período académico (derivada de mes/año)
    CONCAT(LPAD(pa.MES_INICIO, 2, '0'), '/', pa.AÑO_INICIO, ' - ', LPAD(pa.MES_FIN, 2, '0'), '/', pa.AÑO_FIN) AS NOMBRE_PERIODO,
    pa.AÑO_INICIO AS AÑO_ACADEMICO,
    'N/D' AS TIPO_PERIODO,
    NULL AS PERIODO_ESTADO,
    CONCAT(LPAD(pa.MES_INICIO, 2, '0'), '/', pa.AÑO_INICIO, ' - ', LPAD(pa.MES_FIN, 2, '0'), '/', pa.AÑO_FIN) AS PERIODO_COMPLETO,
    
    -- Información del estudiante
    CONCAT(persona.NOMBRE, ' ', persona.APELLIDO) as ESTUDIANTE_NOMBRE,
    persona.CEDULA as CEDULA_ESTUDIANTE,
    c.NOMBRE as CARRERA_NOMBRE,
    e.SEMESTRE_ACTUAL,
    
    -- Información de la entidad receptora
    ic.NOMBRE as ENTIDAD_RECEPTORA,
    ic.CIUDAD as ENTIDAD_CIUDAD,
    
    -- Información del instructor
    CONCAT(inst_persona.NOMBRE, ' ', inst_persona.APELLIDO) as INSTRUCTOR_NOMBRE,
    inst.ESPECIALIDAD as INSTRUCTOR_ESPECIALIDAD

FROM TAB_SERVICIO_COMUNITARIO sc
LEFT JOIN TAB_PERIODOS_ACADEMICOS pa ON sc.ID_PERIODO_ACADEMICO = pa.ID_PERIODO_ACADEMICO
LEFT JOIN TAB_ESTUDIANTES e ON sc.ID_ESTUDIANTE = e.ID_ESTUDIANTE
LEFT JOIN TAB_DATOS_PERSONAS persona ON e.ID_DATO_PERSONA = persona.ID_DATO_PERSONA
LEFT JOIN TAB_CARRERAS c ON e.ID_CARRERA = c.ID_CARRERA
LEFT JOIN TAB_INSTITUCIONES_CONVENIOS ic ON sc.ID_INSTITUCION_CONVENIO = ic.ID_INSTITUCION_CONVENIO
LEFT JOIN TAB_INSTRUCTORES inst ON sc.ID_INSTRUCTOR = inst.ID_INSTRUCTOR
LEFT JOIN TAB_DATOS_PERSONAS inst_persona ON inst.ID_DATO_PERSONA = inst_persona.ID_DATO_PERSONA
ORDER BY pa.AÑO_INICIO DESC, pa.MES_INICIO DESC, sc.FECHA_INICIO DESC;
-- === Fin vistas ===
-- Vuelve a crear SP_OBTENER_PERIODO_ACTUAL, SP_ESTADISTICAS_PERIODO, SP_DOCUMENTOS_POR_PERIODO
-- desde bddITSI.sql (bloque DELIMITER //) si los usas.