-- Documentos habilitantes PDF por institución (modal Nueva Institución)
CREATE TABLE IF NOT EXISTS TAB_DOCUMENTOS_HABILITANTES_INSTITUCION (
   ID_DOCUMENTO_HABILITANTE int NOT NULL AUTO_INCREMENT,
   ID_INSTITUCION_CONVENIO int NOT NULL,
   NOMBRE_ARCHIVO varchar(255) NOT NULL,
   NOMBRE_ORIGINAL varchar(255) NOT NULL,
   TIPO_ARCHIVO varchar(100) NOT NULL DEFAULT 'application/pdf',
   TAMANO_BYTES int UNSIGNED NULL,
   FECHA_SUBIDA datetime NOT NULL,
   primary key (ID_DOCUMENTO_HABILITANTE),
   key IDX_DOC_HAB_INST (ID_INSTITUCION_CONVENIO),
   constraint FK_DOC_HAB_INSTITUCION foreign key (ID_INSTITUCION_CONVENIO)
      references TAB_INSTITUCIONES_CONVENIOS (ID_INSTITUCION_CONVENIO)
      on delete cascade on update restrict
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
